/*
 * This file is generated by jOOQ.
 */
package com.coyotesong.dojo.youtube.repository.jooq.generatedCache;


import com.coyotesong.dojo.youtube.repository.jooq.generatedCache.tables.YoutubeApiCache;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApiCache extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>api_cache</code>
     */
    public static final ApiCache API_CACHE = new ApiCache();

    /**
     * The table <code>api_cache.youtube_api_cache</code>.
     */
    public final YoutubeApiCache YOUTUBE_API_CACHE = YoutubeApiCache.YOUTUBE_API_CACHE;

    /**
     * No further instances allowed
     */
    private ApiCache() {
        super("api_cache", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            YoutubeApiCache.YOUTUBE_API_CACHE
        );
    }
}
