/*
 * This file is generated by jOOQ.
 */
package com.coyotesong.dojo.youtube.repository.jooq.generatedCache;


import com.coyotesong.dojo.youtube.repository.jooq.generatedCache.tables.YoutubeApiCache;
import com.coyotesong.dojo.youtube.repository.jooq.generatedCache.tables.records.YoutubeApiCacheRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * api_cache.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<YoutubeApiCacheRecord> YOUTUBE_API_CACHE_PKEY = Internal.createUniqueKey(YoutubeApiCache.YOUTUBE_API_CACHE, DSL.name("youtube_api_cache_pkey"), new TableField[] { YoutubeApiCache.YOUTUBE_API_CACHE.KEY }, true);
}
