/*
 * This file is generated by jOOQ.
 */
package com.coyotesong.dojo.youtube.repository.jooq.generatedCache;


import com.coyotesong.dojo.youtube.repository.jooq.generatedCache.tables.YoutubeApiCache;


/**
 * Convenience access to all tables in api_cache.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>api_cache.youtube_api_cache</code>.
     */
    public static final YoutubeApiCache YOUTUBE_API_CACHE = YoutubeApiCache.YOUTUBE_API_CACHE;
}
