spring:
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: default
    # active: production

# server.error.whitelabel.enabled=false
# server.error.path=/error