/*
 * This file is generated by jOOQ.
 */
package com.coyotesong.dojo.youtube.repository.jooq.generatedCache.tables.records;


import com.coyotesong.dojo.youtube.repository.jooq.generatedCache.tables.YoutubeApiCache;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class YoutubeApiCacheRecord extends UpdatableRecordImpl<YoutubeApiCacheRecord> implements Record14<Integer, JSON, String, String, String, String, Integer, Integer, String, String, String, JSON, String, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_cache.youtube_api_cache.key</code>.
     */
    public void setKey(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.key</code>.
     */
    public Integer getKey() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.request_json</code>.
     */
    public void setRequestJson(JSON value) {
        set(1, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.request_json</code>.
     */
    public JSON getRequestJson() {
        return (JSON) get(1);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.kind</code>.
     */
    public void setKind(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.kind</code>.
     */
    public String getKind() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.region_code</code>.
     */
    public void setRegionCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.region_code</code>.
     */
    public String getRegionCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.event_id</code>.
     */
    public void setEventId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.event_id</code>.
     */
    public String getEventId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.visitor_id</code>.
     */
    public void setVisitorId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.visitor_id</code>.
     */
    public String getVisitorId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.results_per_page</code>.
     */
    public void setResultsPerPage(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.results_per_page</code>.
     */
    public Integer getResultsPerPage() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.total_results</code>.
     */
    public void setTotalResults(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.total_results</code>.
     */
    public Integer getTotalResults() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.page_token</code>.
     */
    public void setPageToken(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.page_token</code>.
     */
    public String getPageToken() {
        return (String) get(8);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.next_page_token</code>.
     */
    public void setNextPageToken(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.next_page_token</code>.
     */
    public String getNextPageToken() {
        return (String) get(9);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.prev_page_token</code>.
     */
    public void setPrevPageToken(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.prev_page_token</code>.
     */
    public String getPrevPageToken() {
        return (String) get(10);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.content</code>.
     */
    public void setContent(JSON value) {
        set(11, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.content</code>.
     */
    public JSON getContent() {
        return (JSON) get(11);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.etag</code>.
     */
    public void setEtag(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.etag</code>.
     */
    public String getEtag() {
        return (String) get(12);
    }

    /**
     * Setter for <code>api_cache.youtube_api_cache.last_updated</code>.
     */
    public void setLastUpdated(Instant value) {
        set(13, value);
    }

    /**
     * Getter for <code>api_cache.youtube_api_cache.last_updated</code>.
     */
    public Instant getLastUpdated() {
        return (Instant) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, JSON, String, String, String, String, Integer, Integer, String, String, String, JSON, String, Instant> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, JSON, String, String, String, String, Integer, Integer, String, String, String, JSON, String, Instant> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.KEY;
    }

    @Override
    public Field<JSON> field2() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.REQUEST_JSON;
    }

    @Override
    public Field<String> field3() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.KIND;
    }

    @Override
    public Field<String> field4() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.REGION_CODE;
    }

    @Override
    public Field<String> field5() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.EVENT_ID;
    }

    @Override
    public Field<String> field6() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.VISITOR_ID;
    }

    @Override
    public Field<Integer> field7() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.RESULTS_PER_PAGE;
    }

    @Override
    public Field<Integer> field8() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.TOTAL_RESULTS;
    }

    @Override
    public Field<String> field9() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.PAGE_TOKEN;
    }

    @Override
    public Field<String> field10() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.NEXT_PAGE_TOKEN;
    }

    @Override
    public Field<String> field11() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.PREV_PAGE_TOKEN;
    }

    @Override
    public Field<JSON> field12() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.CONTENT;
    }

    @Override
    public Field<String> field13() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.ETAG;
    }

    @Override
    public Field<Instant> field14() {
        return YoutubeApiCache.YOUTUBE_API_CACHE.LAST_UPDATED;
    }

    @Override
    public Integer component1() {
        return getKey();
    }

    @Override
    public JSON component2() {
        return getRequestJson();
    }

    @Override
    public String component3() {
        return getKind();
    }

    @Override
    public String component4() {
        return getRegionCode();
    }

    @Override
    public String component5() {
        return getEventId();
    }

    @Override
    public String component6() {
        return getVisitorId();
    }

    @Override
    public Integer component7() {
        return getResultsPerPage();
    }

    @Override
    public Integer component8() {
        return getTotalResults();
    }

    @Override
    public String component9() {
        return getPageToken();
    }

    @Override
    public String component10() {
        return getNextPageToken();
    }

    @Override
    public String component11() {
        return getPrevPageToken();
    }

    @Override
    public JSON component12() {
        return getContent();
    }

    @Override
    public String component13() {
        return getEtag();
    }

    @Override
    public Instant component14() {
        return getLastUpdated();
    }

    @Override
    public Integer value1() {
        return getKey();
    }

    @Override
    public JSON value2() {
        return getRequestJson();
    }

    @Override
    public String value3() {
        return getKind();
    }

    @Override
    public String value4() {
        return getRegionCode();
    }

    @Override
    public String value5() {
        return getEventId();
    }

    @Override
    public String value6() {
        return getVisitorId();
    }

    @Override
    public Integer value7() {
        return getResultsPerPage();
    }

    @Override
    public Integer value8() {
        return getTotalResults();
    }

    @Override
    public String value9() {
        return getPageToken();
    }

    @Override
    public String value10() {
        return getNextPageToken();
    }

    @Override
    public String value11() {
        return getPrevPageToken();
    }

    @Override
    public JSON value12() {
        return getContent();
    }

    @Override
    public String value13() {
        return getEtag();
    }

    @Override
    public Instant value14() {
        return getLastUpdated();
    }

    @Override
    public YoutubeApiCacheRecord value1(Integer value) {
        setKey(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value2(JSON value) {
        setRequestJson(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value3(String value) {
        setKind(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value4(String value) {
        setRegionCode(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value5(String value) {
        setEventId(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value6(String value) {
        setVisitorId(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value7(Integer value) {
        setResultsPerPage(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value8(Integer value) {
        setTotalResults(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value9(String value) {
        setPageToken(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value10(String value) {
        setNextPageToken(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value11(String value) {
        setPrevPageToken(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value12(JSON value) {
        setContent(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value13(String value) {
        setEtag(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord value14(Instant value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public YoutubeApiCacheRecord values(Integer value1, JSON value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, String value9, String value10, String value11, JSON value12, String value13, Instant value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YoutubeApiCacheRecord
     */
    public YoutubeApiCacheRecord() {
        super(YoutubeApiCache.YOUTUBE_API_CACHE);
    }

    /**
     * Create a detached, initialised YoutubeApiCacheRecord
     */
    public YoutubeApiCacheRecord(Integer key, JSON requestJson, String kind, String regionCode, String eventId, String visitorId, Integer resultsPerPage, Integer totalResults, String pageToken, String nextPageToken, String prevPageToken, JSON content, String etag, Instant lastUpdated) {
        super(YoutubeApiCache.YOUTUBE_API_CACHE);

        setKey(key);
        setRequestJson(requestJson);
        setKind(kind);
        setRegionCode(regionCode);
        setEventId(eventId);
        setVisitorId(visitorId);
        setResultsPerPage(resultsPerPage);
        setTotalResults(totalResults);
        setPageToken(pageToken);
        setNextPageToken(nextPageToken);
        setPrevPageToken(prevPageToken);
        setContent(content);
        setEtag(etag);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }
}
